version: "3.9"

services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    environment:
      WG_HOST: <SERVER_IP>
      PASSWORD: <PANEL-PASSWD>
      WG_MTU: 1420
      WG_PORT: <WG-PUB-PORT>
      WG_DEFAULT_DNS: 172.16.0.4
    volumes:
      - ~/wireguard/.wg-easy:/etc/wireguard
    ports:
      - "<WG-PUB-PORT>1337:51820/udp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    restart: unless-stopped
    networks:
      appnet:
        ipv4_address: 172.16.0.2

  nginx:
    image: nginx
    container_name: nginx
    hostname: nginx
    volumes:
      - ./wg-easy.conf:/etc/nginx/templates/default.conf.template
    restart: unless-stopped
    depends_on:
      - wg-easy
    networks:
      appnet:
        ipv4_address: 172.16.0.3

  bind9:
    container_name: my-dns
    image: ubuntu/bind9:latest
    environment:
      BIND9_USER: root
      TZ: Europe/Moscow
    volumes:
      - ./my_dns/config/:/etc/bind/
      - ./my_dns/cache:/var/cache/bind
      - ./my_dns/records:/var/lib/bind
    restart: unless-stopped
    networks:
      appnet:
        ipv4_address: 172.16.0.4

networks:
  appnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.16.0.0/28"
